// https://gist.github.com/xta/6e9b63db1fa662bb3910b680f9ebd458
// localeIdentifier, Description
module.exports = [
  {code: 'eu', name: 'Basque'},
  {code: 'hr_BA', name: 'Croatian (Bosnia & Herzegovina)'},
  {code: 'en_CM', name: 'English (Cameroon)'},
  {code: 'en_BI', name: 'English (Burundi)'},
  {code: 'rw_RW', name: 'Kinyarwanda (Rwanda)'},
  {code: 'ast', name: 'Asturian'},
  {code: 'en_SZ', name: 'English (Swaziland)'},
  {code: 'he_IL', name: 'Hebrew (Israel)'},
  {code: 'ar', name: 'Arabic'},
  {code: 'uz_Arab', name: 'Uzbek (Arabic)'},
  {code: 'en_PN', name: 'English (Pitcairn Islands)'},
  {code: 'as', name: 'Assamese'},
  {code: 'en_NF', name: 'English (Norfolk Island)'},
  {code: 'ks_IN', name: 'Kashmiri (India)'},
  {code: 'es_KY', name: 'Spanish (Cayman Islands)'},
  {code: 'rwk_TZ', name: 'Rwa (Tanzania)'},
  {code: 'zh_Hant_TW', name: 'Chinese (Traditional, Taiwan)'},
  {code: 'en_CN', name: 'English (China)'},
  {code: 'gsw_LI', name: 'Swiss German (Liechtenstein)'},
  {code: 'ta_IN', name: 'Tamil (India)'},
  {code: 'th_TH', name: 'Thai (Thailand)'},
  {code: 'es_EA', name: 'Spanish (Ceuta & Melilla)'},
  {code: 'fr_GF', name: 'French (French Guiana)'},
  {code: 'ar_001', name: 'Arabic (World)'},
  {code: 'en_RW', name: 'English (Rwanda)'},
  {code: 'tr_TR', name: 'Turkish (Turkey)'},
  {code: 'de_CH', name: 'German (Switzerland)'},
  {code: 'ee_TG', name: 'Ewe (Togo)'},
  {code: 'en_NG', name: 'English (Nigeria)'},
  {code: 'fr_TG', name: 'French (Togo)'},
  {code: 'az', name: 'Azerbaijani'},
  {code: 'fr_SC', name: 'French (Seychelles)'},
  {code: 'es_HN', name: 'Spanish (Honduras)'},
  {code: 'en_AG', name: 'English (Antigua & Barbuda)'},
  {code: 'ru_KZ', name: 'Russian (Kazakhstan)'},
  {code: 'gsw', name: 'Swiss German'},
  {code: 'dyo', name: 'Jola-Fonyi'},
  {code: 'so_ET', name: 'Somali (Ethiopia)'},
  {code: 'zh_Hant_MO', name: 'Chinese (Traditional, Macau [China])'},
  {code: 'de_BE', name: 'German (Belgium)'},
  {code: 'nus_SS', name: 'Nuer (South Sudan)'},
  {code: 'km_KH', name: 'Khmer (Cambodia)'},
  {code: 'my_MM', name: 'Burmese (Myanmar [Burma])'},
  {code: 'mgh_MZ', name: 'Makhuwa-Meetto (Mozambique)'},
  {code: 'ee_GH', name: 'Ewe (Ghana)'},
  {code: 'es_EC', name: 'Spanish (Ecuador)'},
  {code: 'kw_GB', name: 'Cornish (United Kingdom)'},
  {code: 'rm_CH', name: 'Romansh (Switzerland)'},
  {code: 'en_ME', name: 'English (Montenegro)'},
  {code: 'nyn', name: 'Nyankole'},
  {code: 'mk_MK', name: 'Macedonian (Macedonia)'},
  {code: 'bs_Cyrl_BA', name: 'Bosnian (Cyrillic, Bosnia & Herzegovina)'},
  {code: 'ar_MR', name: 'Arabic (Mauritania)'},
  {code: 'es_GL', name: 'Spanish (Greenland)'},
  {code: 'en_BM', name: 'English (Bermuda)'},
  {code: 'ms_Arab', name: 'Malay (Arabic)'},
  {code: 'en_AI', name: 'English (Anguilla)'},
  {code: 'gl_ES', name: 'Galician (Spain)'},
  {code: 'en_PR', name: 'English (Puerto Rico)'},
  {code: 'ff_CM', name: 'Fulah (Cameroon)'},
  {code: 'ne_IN', name: 'Nepali (India)'},
  {code: 'or_IN', name: 'Odia (India)'},
  {code: 'khq_ML', name: 'Koyra Chiini (Mali)'},
  {code: 'en_MG', name: 'English (Madagascar)'},
  {code: 'pt_TL', name: 'Portuguese (Timor-Leste)'},
  {code: 'en_LC', name: 'English (St. Lucia)'},
  {code: 'iu_CA', name: 'Inuktitut (Canada)'},
  {code: 'ta_SG', name: 'Tamil (Singapore)'},
  {code: 'jmc_TZ', name: 'Machame (Tanzania)'},
  {code: 'om_ET', name: 'Oromo (Ethiopia)'},
  {code: 'lv_LV', name: 'Latvian (Latvia)'},
  {code: 'es_US', name: 'Spanish (United States)'},
  {code: 'en_PT', name: 'English (Portugal)'},
  {code: 'vai_Latn_LR', name: 'Vai (Latin, Liberia)'},
  {code: 'en_NL', name: 'English (Netherlands)'},
  {code: 'to_TO', name: 'Tongan (Tonga)'},
  {code: 'cgg_UG', name: 'Chiga (Uganda)'},
  {code: 'en_MH', name: 'English (Marshall Islands)'},
  {code: 'ta', name: 'Tamil'},
  {code: 'zu_ZA', name: 'Zulu (South Africa)'},
  {code: 'shi_Latn_MA', name: 'Tachelhit (Latin, Morocco)'},
  {code: 'es_FK', name: 'Spanish (Falkland Islands)'},
  {code: 'ar_KM', name: 'Arabic (Comoros)'},
  {code: 'en_AL', name: 'English (Albania)'},
  {code: 'brx_IN', name: 'Bodo (India)'},
  {code: 'te', name: 'Telugu'},
  {code: 'chr_US', name: 'Cherokee (United States)'},
  {code: 'yo_BJ', name: 'Yoruba (Benin)'},
  {code: 'fr_VU', name: 'French (Vanuatu)'},
  {code: 'pa', name: 'Punjabi'},
  {code: 'tg', name: 'Tajik'},
  {code: 'kea', name: 'Kabuverdianu'},
  {code: 'ksh_DE', name: 'Colognian (Germany)'},
  {code: 'sw_CD', name: 'Swahili (Congo - Kinshasa)'},
  {code: 'te_IN', name: 'Telugu (India)'},
  {code: 'fr_RE', name: 'French (Réunion)'},
  {code: 'th', name: 'Thai'},
  {code: 'ur_IN', name: 'Urdu (India)'},
  {code: 'yo_NG', name: 'Yoruba (Nigeria)'},
  {code: 'ti', name: 'Tigrinya'},
  {code: 'es_HT', name: 'Spanish (Haiti)'},
  {code: 'es_GP', name: 'Spanish (Guadeloupe)'},
  {code: 'guz_KE', name: 'Gusii (Kenya)'},
  {code: 'tk', name: 'Turkmen'},
  {code: 'kl_GL', name: 'Kalaallisut (Greenland)'},
  {code: 'ksf_CM', name: 'Bafia (Cameroon)'},
  {code: 'mua_CM', name: 'Mundang (Cameroon)'},
  {code: 'lag_TZ', name: 'Langi (Tanzania)'},
  {code: 'lb', name: 'Luxembourgish'},
  {code: 'fr_TN', name: 'French (Tunisia)'},
  {code: 'es_PA', name: 'Spanish (Panama)'},
  {code: 'pl_PL', name: 'Polish (Poland)'},
  {code: 'to', name: 'Tongan'},
  {code: 'hi_IN', name: 'Hindi (India)'},
  {code: 'dje_NE', name: 'Zarma (Niger)'},
  {code: 'es_GQ', name: 'Spanish (Equatorial Guinea)'},
  {code: 'en_BR', name: 'English (Brazil)'},
  {code: 'kok_IN', name: 'Konkani (India)'},
  {code: 'pl', name: 'Polish'},
  {code: 'fr_GN', name: 'French (Guinea)'},
  {code: 'bem', name: 'Bemba'},
  {code: 'ha', name: 'Hausa'},
  {code: 'ckb', name: 'Central Kurdish'},
  {code: 'lg', name: 'Ganda'},
  {code: 'tr', name: 'Turkish'},
  {code: 'en_PW', name: 'English (Palau)'},
  {code: 'en_NO', name: 'English (Norway)'},
  {code: 'nyn_UG', name: 'Nyankole (Uganda)'},
  {code: 'sr_Latn_RS', name: 'Serbian (Latin, Serbia)'},
  {code: 'gsw_FR', name: 'Swiss German (France)'},
  {code: 'pa_Guru', name: 'Punjabi (Gurmukhi)'},
  {code: 'he', name: 'Hebrew'},
  {code: 'qu_BO', name: 'Quechua (Bolivia)'},
  {code: 'ps_AF', name: 'Pashto (Afghanistan)'},
  {code: 'lu_CD', name: 'Luba-Katanga (Congo - Kinshasa)'},
  {code: 'mgo_CM', name: 'Metaʼ (Cameroon)'},
  {code: 'sn_ZW', name: 'Shona (Zimbabwe)'},
  {code: 'en_BS', name: 'English (Bahamas)'},
  {code: 'da', name: 'Danish'},
  {code: 'ps', name: 'Pashto'},
  {code: 'ln', name: 'Lingala'},
  {code: 'pt', name: 'Portuguese'},
  {code: 'hi', name: 'Hindi'},
  {code: 'lo', name: 'Lao'},
  {code: 'ebu', name: 'Embu'},
  {code: 'de', name: 'German'},
  {code: 'gu_IN', name: 'Gujarati (India)'},
  {code: 'seh', name: 'Sena'},
  {code: 'en_CX', name: 'English (Christmas Island)'},
  {code: 'en_ZM', name: 'English (Zambia)'},
  {code: 'fr_HT', name: 'French (Haiti)'},
  {code: 'fr_GP', name: 'French (Guadeloupe)'},
  {code: 'pt_GQ', name: 'Portuguese (Equatorial Guinea)'},
  {code: 'lt', name: 'Lithuanian'},
  {code: 'lu', name: 'Luba-Katanga'},
  {code: 'es_TT', name: 'Spanish (Trinidad & Tobago)'},
  {code: 'ln_CD', name: 'Lingala (Congo - Kinshasa)'},
  {code: 'vai_Latn', name: 'Vai (Latin)'},
  {code: 'el_GR', name: 'Greek (Greece)'},
  {code: 'lv', name: 'Latvian'},
  {code: 'en_KE', name: 'English (Kenya)'},
  {code: 'sbp', name: 'Sangu'},
  {code: 'hr', name: 'Croatian'},
  {code: 'en_CY', name: 'English (Cyprus)'},
  {code: 'es_GT', name: 'Spanish (Guatemala)'},
  {code: 'twq_NE', name: 'Tasawaq (Niger)'},
  {code: 'zh_Hant_HK', name: 'Chinese (Traditional, Hong Kong [China])'},
  {code: 'kln_KE', name: 'Kalenjin (Kenya)'},
  {code: 'fr_GQ', name: 'French (Equatorial Guinea)'},
  {code: 'chr', name: 'Cherokee'},
  {code: 'hu', name: 'Hungarian'},
  {code: 'es_UY', name: 'Spanish (Uruguay)'},
  {code: 'fr_CA', name: 'French (Canada)'},
  {code: 'ms_BN', name: 'Malay (Brunei)'},
  {code: 'en_NR', name: 'English (Nauru)'},
  {code: 'mer', name: 'Meru'},
  {code: 'shi', name: 'Tachelhit'},
  {code: 'es_PE', name: 'Spanish (Peru)'},
  {code: 'fr_SN', name: 'French (Senegal)'},
  {code: 'bez', name: 'Bena'},
  {code: 'sw_TZ', name: 'Swahili (Tanzania)'},
  {code: 'wae_CH', name: 'Walser (Switzerland)'},
  {code: 'kkj', name: 'Kako'},
  {code: 'hy', name: 'Armenian'},
  {code: 'dz_BT', name: 'Dzongkha (Bhutan)'},
  {code: 'en_CZ', name: 'English (Czechia)'},
  {code: 'teo_KE', name: 'Teso (Kenya)'},
  {code: 'teo', name: 'Teso'},
  {code: 'en_AR', name: 'English (Argentina)'},
  {code: 'ar_JO', name: 'Arabic (Jordan)'},
  {code: 'yue_Hans_CN', name: 'Cantonese (Simplified, China)'},
  {code: 'mer_KE', name: 'Meru (Kenya)'},
  {code: 'khq', name: 'Koyra Chiini'},
  {code: 'ln_CF', name: 'Lingala (Central African Republic)'},
  {code: 'nn_NO', name: 'Norwegian Nynorsk (Norway)'},
  {code: 'es_SR', name: 'Spanish (Suriname)'},
  {code: 'en_MO', name: 'English (Macau [China])'},
  {code: 'ar_TD', name: 'Arabic (Chad)'},
  {code: 'dz', name: 'Dzongkha'},
  {code: 'ses', name: 'Koyraboro Senni'},
  {code: 'en_BW', name: 'English (Botswana)'},
  {code: 'en_AS', name: 'English (American Samoa)'},
  {code: 'ar_IL', name: 'Arabic (Israel)'},
  {code: 'es_BB', name: 'Spanish (Barbados)'},
  {code: 'bo_CN', name: 'Tibetan (China)'},
  {code: 'nnh', name: 'Ngiemboon'},
  {code: 'teo_UG', name: 'Teso (Uganda)'},
  {code: 'hy_AM', name: 'Armenian (Armenia)'},
  {code: 'ln_CG', name: 'Lingala (Congo - Brazzaville)'},
  {code: 'sr_Latn_BA', name: 'Serbian (Latin, Bosnia & Herzegovina)'},
  {code: 'en_MP', name: 'English (Northern Mariana Islands)'},
  {code: 'ksb_TZ', name: 'Shambala (Tanzania)'},
  {code: 'ar_SA', name: 'Arabic (Saudi Arabia)'},
  {code: 'smn_FI', name: 'Inari Sami (Finland)'},
  {code: 'ar_LY', name: 'Arabic (Libya)'},
  {code: 'en_AT', name: 'English (Austria)'},
  {code: 'so_KE', name: 'Somali (Kenya)'},
  {code: 'fr_CD', name: 'French (Congo - Kinshasa)'},
  {code: 'af_NA', name: 'Afrikaans (Namibia)'},
  {code: 'en_NU', name: 'English (Niue)'},
  {code: 'es_PH', name: 'Spanish (Philippines)'},
  {code: 'en_KI', name: 'English (Kiribati)'},
  {code: 'en_JE', name: 'English (Jersey)'},
  {code: 'lkt', name: 'Lakota'},
  {code: 'en_AU', name: 'English (Australia)'},
  {code: 'fa_IR', name: 'Persian (Iran)'},
  {code: 'pt_FR', name: 'Portuguese (France)'},
  {code: 'uz_Latn_UZ', name: 'Uzbek (Latin, Uzbekistan)'},
  {code: 'zh_Hans_CN', name: 'Chinese (Simplified, China)'},
  {code: 'ewo_CM', name: 'Ewondo (Cameroon)'},
  {code: 'fr_PF', name: 'French (French Polynesia)'},
  {code: 'ca_IT', name: 'Catalan (Italy)'},
  {code: 'es_GY', name: 'Spanish (Guyana)'},
  {code: 'en_BZ', name: 'English (Belize)'},
  {code: 'ar_KW', name: 'Arabic (Kuwait)'},
  {code: 'pt_GW', name: 'Portuguese (Guinea-Bissau)'},
  {code: 'fr_FR', name: 'French (France)'},
  {code: 'am_ET', name: 'Amharic (Ethiopia)'},
  {code: 'en_VC', name: 'English (St. Vincent & Grenadines)'},
  {code: 'es_DM', name: 'Spanish (Dominica)'},
  {code: 'fr_DJ', name: 'French (Djibouti)'},
  {code: 'fr_CF', name: 'French (Central African Republic)'},
  {code: 'es_SV', name: 'Spanish (El Salvador)'},
  {code: 'en_MS', name: 'English (Montserrat)'},
  {code: 'pt_ST', name: 'Portuguese (São Tomé & Príncipe)'},
  {code: 'ar_SD', name: 'Arabic (Sudan)'},
  {code: 'luy_KE', name: 'Luyia (Kenya)'},
  {code: 'gd_GB', name: 'Scottish Gaelic (United Kingdom)'},
  {code: 'de_LI', name: 'German (Liechtenstein)'},
  {code: 'it_VA', name: 'Italian (Vatican City)'},
  {code: 'fr_CG', name: 'French (Congo - Brazzaville)'},
  {code: 'pt_CH', name: 'Portuguese (Switzerland)'},
  {code: 'ckb_IQ', name: 'Central Kurdish (Iraq)'},
  {code: 'zh_Hans_SG', name: 'Chinese (Simplified, Singapore)'},
  {code: 'en_MT', name: 'English (Malta)'},
  {code: 'ha_NE', name: 'Hausa (Niger)'},
  {code: 'en_ID', name: 'English (Indonesia)'},
  {code: 'ewo', name: 'Ewondo'},
  {code: 'af_ZA', name: 'Afrikaans (South Africa)'},
  {code: 'os_GE', name: 'Ossetic (Georgia)'},
  {code: 'om_KE', name: 'Oromo (Kenya)'},
  {code: 'nl_SR', name: 'Dutch (Suriname)'},
  {code: 'es_ES', name: 'Spanish (Spain)'},
  {code: 'es_DO', name: 'Spanish (Dominican Republic)'},
  {code: 'ar_IQ', name: 'Arabic (Iraq)'},
  {code: 'fr_CH', name: 'French (Switzerland)'},
  {code: 'nnh_CM', name: 'Ngiemboon (Cameroon)'},
  {code: 'es_SX', name: 'Spanish (Sint Maarten)'},
  {code: 'es_419', name: 'Spanish (Latin America)'},
  {code: 'en_MU', name: 'English (Mauritius)'},
  {code: 'en_US_POSIX', name: 'English (United States, Computer)'},
  {code: 'yav_CM', name: 'Yangben (Cameroon)'},
  {code: 'luo_KE', name: 'Luo (Kenya)'},
  {code: 'dua_CM', name: 'Duala (Cameroon)'},
  {code: 'et_EE', name: 'Estonian (Estonia)'},
  {code: 'en_IE', name: 'English (Ireland)'},
  {code: 'ak_GH', name: 'Akan (Ghana)'},
  {code: 'rwk', name: 'Rwa'},
  {code: 'es_CL', name: 'Spanish (Chile)'},
  {code: 'kea_CV', name: 'Kabuverdianu (Cape Verde)'},
  {code: 'fr_CI', name: 'French (Côte d’Ivoire)'},
  {code: 'ckb_IR', name: 'Central Kurdish (Iran)'},
  {code: 'fr_BE', name: 'French (Belgium)'},
  {code: 'se', name: 'Northern Sami'},
  {code: 'en_NZ', name: 'English (New Zealand)'},
  {code: 'en_MV', name: 'English (Maldives)'},
  {code: 'en_LR', name: 'English (Liberia)'},
  {code: 'es_PM', name: 'Spanish (St. Pierre & Miquelon)'},
  {code: 'en_KN', name: 'English (St. Kitts & Nevis)'},
  {code: 'nb_SJ', name: 'Norwegian Bokmål (Svalbard & Jan Mayen)'},
  {code: 'ha_NG', name: 'Hausa (Nigeria)'},
  {code: 'sg', name: 'Sango'},
  {code: 'sr_Cyrl_RS', name: 'Serbian (Cyrillic, Serbia)'},
  {code: 'ru_RU', name: 'Russian (Russia)'},
  {code: 'en_ZW', name: 'English (Zimbabwe)'},
  {code: 'sv_AX', name: 'Swedish (Åland Islands)'},
  {code: 'si', name: 'Sinhala'},
  {code: 'ga_IE', name: 'Irish (Ireland)'},
  {code: 'en_VG', name: 'English (British Virgin Islands)'},
  {code: 'ff_MR', name: 'Fulah (Mauritania)'},
  {code: 'sk', name: 'Slovak'},
  {code: 'ky_KG', name: 'Kyrgyz (Kyrgyzstan)'},
  {code: 'agq_CM', name: 'Aghem (Cameroon)'},
  {code: 'mzn', name: 'Mazanderani'},
  {code: 'fr_BF', name: 'French (Burkina Faso)'},
  {code: 'mr_IN', name: 'Marathi (India)'},
  {code: 'en_MW', name: 'English (Malawi)'},
  {code: 'de_AT', name: 'German (Austria)'},
  {code: 'az_Latn', name: 'Azerbaijani (Latin)'},
  {code: 'en_LS', name: 'English (Lesotho)'},
  {code: 'ka', name: 'Georgian'},
  {code: 'naq_NA', name: 'Nama (Namibia)'},
  {code: 'sl', name: 'Slovenian'},
  {code: 'sn', name: 'Shona'},
  {code: 'sr_Latn_ME', name: 'Serbian (Latin, Montenegro)'},
  {code: 'fr_NC', name: 'French (New Caledonia)'},
  {code: 'so', name: 'Somali'},
  {code: 'is_IS', name: 'Icelandic (Iceland)'},
  {code: 'twq', name: 'Tasawaq'},
  {code: 'ig_NG', name: 'Igbo (Nigeria)'},
  {code: 'sq', name: 'Albanian'},
  {code: 'fo_FO', name: 'Faroese (Faroe Islands)'},
  {code: 'sr', name: 'Serbian'},
  {code: 'tzm', name: 'Central Atlas Tamazight'},
  {code: 'ga', name: 'Irish'},
  {code: 'om', name: 'Oromo'},
  {code: 'en_LT', name: 'English (Lithuania)'},
  {code: 'bas_CM', name: 'Basaa (Cameroon)'},
  {code: 'se_NO', name: 'Northern Sami (Norway)'},
  {code: 'ki', name: 'Kikuyu'},
  {code: 'nl_BE', name: 'Dutch (Belgium)'},
  {code: 'ar_QA', name: 'Arabic (Qatar)'},
  {code: 'gd', name: 'Scottish Gaelic'},
  {code: 'sv', name: 'Swedish'},
  {code: 'kk', name: 'Kazakh'},
  {code: 'rn_BI', name: 'Rundi (Burundi)'},
  {code: 'es_CO', name: 'Spanish (Colombia)'},
  {code: 'az_Latn_AZ', name: 'Azerbaijani (Latin, Azerbaijan)'},
  {code: 'kl', name: 'Kalaallisut'},
  {code: 'or', name: 'Odia'},
  {code: 'es_AG', name: 'Spanish (Antigua & Barbuda)'},
  {code: 'ca', name: 'Catalan'},
  {code: 'en_VI', name: 'English (U.S. Virgin Islands)'},
  {code: 'km', name: 'Khmer'},
  {code: 'os', name: 'Ossetic'},
  {code: 'sw', name: 'Swahili'},
  {code: 'en_MY', name: 'English (Malaysia)'},
  {code: 'kn', name: 'Kannada'},
  {code: 'en_LU', name: 'English (Luxembourg)'},
  {code: 'fr_SY', name: 'French (Syria)'},
  {code: 'ar_TN', name: 'Arabic (Tunisia)'},
  {code: 'en_JM', name: 'English (Jamaica)'},
  {code: 'fr_PM', name: 'French (St. Pierre & Miquelon)'},
  {code: 'ko', name: 'Korean'},
  {code: 'fr_NE', name: 'French (Niger)'},
  {code: 'ce', name: 'Chechen'},
  {code: 'fr_MA', name: 'French (Morocco)'},
  {code: 'gl', name: 'Galician'},
  {code: 'ru_MD', name: 'Russian (Moldova)'},
  {code: 'es_BL', name: 'Spanish (St. Barthélemy)'},
  {code: 'saq_KE', name: 'Samburu (Kenya)'},
  {code: 'ks', name: 'Kashmiri'},
  {code: 'fr_CM', name: 'French (Cameroon)'},
  {code: 'lb_LU', name: 'Luxembourgish (Luxembourg)'},
  {code: 'gv_IM', name: 'Manx (Isle of Man)'},
  {code: 'fr_BI', name: 'French (Burundi)'},
  {code: 'en_LV', name: 'English (Latvia)'},
  {code: 'en_KR', name: 'English (South Korea)'},
  {code: 'es_NI', name: 'Spanish (Nicaragua)'},
  {code: 'en_GB', name: 'English (United Kingdom)'},
  {code: 'kw', name: 'Cornish'},
  {code: 'nl_SX', name: 'Dutch (Sint Maarten)'},
  {code: 'dav_KE', name: 'Taita (Kenya)'},
  {code: 'tr_CY', name: 'Turkish (Cyprus)'},
  {code: 'ky', name: 'Kyrgyz'},
  {code: 'en_UG', name: 'English (Uganda)'},
  {code: 'es_BM', name: 'Spanish (Bermuda)'},
  {code: 'en_TC', name: 'English (Turks & Caicos Islands)'},
  {code: 'es_AI', name: 'Spanish (Anguilla)'},
  {code: 'ar_EG', name: 'Arabic (Egypt)'},
  {code: 'fr_BJ', name: 'French (Benin)'},
  {code: 'gu', name: 'Gujarati'},
  {code: 'es_PR', name: 'Spanish (Puerto Rico)'},
  {code: 'fr_RW', name: 'French (Rwanda)'},
  {code: 'gv', name: 'Manx'},
  {code: 'lrc_IQ', name: 'Northern Luri (Iraq)'},
  {code: 'sr_Cyrl_BA', name: 'Serbian (Cyrillic, Bosnia & Herzegovina)'},
  {code: 'es_MF', name: 'Spanish (St. Martin)'},
  {code: 'fr_MC', name: 'French (Monaco)'},
  {code: 'cs', name: 'Czech'},
  {code: 'bez_TZ', name: 'Bena (Tanzania)'},
  {code: 'es_CR', name: 'Spanish (Costa Rica)'},
  {code: 'asa_TZ', name: 'Asu (Tanzania)'},
  {code: 'ar_EH', name: 'Arabic (Western Sahara)'},
  {code: 'fo_DK', name: 'Faroese (Denmark)'},
  {code: 'ms_Arab_BN', name: 'Malay (Arabic, Brunei)'},
  {code: 'en_JP', name: 'English (Japan)'},
  {code: 'sbp_TZ', name: 'Sangu (Tanzania)'},
  {code: 'en_IL', name: 'English (Israel)'},
  {code: 'lt_LT', name: 'Lithuanian (Lithuania)'},
  {code: 'mfe', name: 'Morisyen'},
  {code: 'en_GD', name: 'English (Grenada)'},
  {code: 'es_LC', name: 'Spanish (St. Lucia)'},
  {code: 'cy', name: 'Welsh'},
  {code: 'ug_CN', name: 'Uyghur (China)'},
  {code: 'ca_FR', name: 'Catalan (France)'},
  {code: 'es_BO', name: 'Spanish (Bolivia)'},
  {code: 'en_SA', name: 'English (Saudi Arabia)'},
  {code: 'fr_BL', name: 'French (St. Barthélemy)'},
  {code: 'bn_IN', name: 'Bangla (India)'},
  {code: 'uz_Cyrl_UZ', name: 'Uzbek (Cyrillic, Uzbekistan)'},
  {code: 'lrc_IR', name: 'Northern Luri (Iran)'},
  {code: 'az_Cyrl', name: 'Azerbaijani (Cyrillic)'},
  {code: 'en_IM', name: 'English (Isle of Man)'},
  {code: 'sw_KE', name: 'Swahili (Kenya)'},
  {code: 'en_SB', name: 'English (Solomon Islands)'},
  {code: 'pa_Arab', name: 'Punjabi (Arabic)'},
  {code: 'ur_PK', name: 'Urdu (Pakistan)'},
  {code: 'haw_US', name: 'Hawaiian (United States)'},
  {code: 'ar_SO', name: 'Arabic (Somalia)'},
  {code: 'en_IN', name: 'English (India)'},
  {code: 'fil', name: 'Filipino'},
  {code: 'fr_MF', name: 'French (St. Martin)'},
  {code: 'en_WS', name: 'English (Samoa)'},
  {code: 'es_CU', name: 'Spanish (Cuba)'},
  {code: 'es_BQ', name: 'Spanish (Caribbean Netherlands)'},
  {code: 'ja_JP', name: 'Japanese (Japan)'},
  {code: 'fy_NL', name: 'Western Frisian (Netherlands)'},
  {code: 'en_SC', name: 'English (Seychelles)'},
  {code: 'yue_Hant_HK', name: 'Cantonese (Traditional, Hong Kong [China])'},
  {code: 'en_IO', name: 'English (British Indian Ocean Territory)'},
  {code: 'pt_PT', name: 'Portuguese (Portugal)'},
  {code: 'en_HK', name: 'English (Hong Kong [China])'},
  {code: 'en_GG', name: 'English (Guernsey)'},
  {code: 'fr_MG', name: 'French (Madagascar)'},
  {code: 'de_LU', name: 'German (Luxembourg)'},
  {code: 'tzm_MA', name: 'Central Atlas Tamazight (Morocco)'},
  {code: 'es_BR', name: 'Spanish (Brazil)'},
  {code: 'en_TH', name: 'English (Thailand)'},
  {code: 'en_SD', name: 'English (Sudan)'},
  {code: 'nds_DE', name: 'Low German (Germany)'},
  {code: 'shi_Tfng', name: 'Tachelhit (Tifinagh)'},
  {code: 'ln_AO', name: 'Lingala (Angola)'},
  {code: 'as_IN', name: 'Assamese (India)'},
  {code: 'en_GH', name: 'English (Ghana)'},
  {code: 'ms_MY', name: 'Malay (Malaysia)'},
  {code: 'ro_RO', name: 'Romanian (Romania)'},
  {code: 'jgo_CM', name: 'Ngomba (Cameroon)'},
  {code: 'es_CW', name: 'Spanish (Curaçao)'},
  {code: 'dua', name: 'Duala'},
  {code: 'en_UM', name: 'English (U.S. Outlying Islands)'},
  {code: 'es_BS', name: 'Spanish (Bahamas)'},
  {code: 'en_SE', name: 'English (Sweden)'},
  {code: 'kn_IN', name: 'Kannada (India)'},
  {code: 'en_KY', name: 'English (Cayman Islands)'},
  {code: 'vun_TZ', name: 'Vunjo (Tanzania)'},
  {code: 'kln', name: 'Kalenjin'},
  {code: 'lrc', name: 'Northern Luri'},
  {code: 'en_GI', name: 'English (Gibraltar)'},
  {code: 'ca_ES', name: 'Catalan (Spain)'},
  {code: 'rof', name: 'Rombo'},
  {code: 'pt_CV', name: 'Portuguese (Cape Verde)'},
  {code: 'kok', name: 'Konkani'},
  {code: 'pt_BR', name: 'Portuguese (Brazil)'},
  {code: 'ar_DJ', name: 'Arabic (Djibouti)'},
  {code: 'yi_001', name: 'Yiddish (World)'},
  {code: 'fi_FI', name: 'Finnish (Finland)'},
  {code: 'zh', name: 'Chinese'},
  {code: 'es_PY', name: 'Spanish (Paraguay)'},
  {code: 'ar_SS', name: 'Arabic (South Sudan)'},
  {code: 'mua', name: 'Mundang'},
  {code: 'sr_Cyrl_ME', name: 'Serbian (Cyrillic, Montenegro)'},
  {code: 'vai_Vaii_LR', name: 'Vai (Vai, Liberia)'},
  {code: 'en_001', name: 'English (World)'},
  {code: 'nl_NL', name: 'Dutch (Netherlands)'},
  {code: 'en_TK', name: 'English (Tokelau)'},
  {code: 'si_LK', name: 'Sinhala (Sri Lanka)'},
  {code: 'en_SG', name: 'English (Singapore)'},
  {code: 'fr_DZ', name: 'French (Algeria)'},
  {code: 'ca_AD', name: 'Catalan (Andorra)'},
  {code: 'sv_SE', name: 'Swedish (Sweden)'},
  {code: 'pt_AO', name: 'Portuguese (Angola)'},
  {code: 'vi', name: 'Vietnamese'},
  {code: 'xog_UG', name: 'Soga (Uganda)'},
  {code: 'xog', name: 'Soga'},
  {code: 'en_IS', name: 'English (Iceland)'},
  {code: 'nb', name: 'Norwegian Bokmål'},
  {code: 'seh_MZ', name: 'Sena (Mozambique)'},
  {code: 'es_AR', name: 'Spanish (Argentina)'},
  {code: 'sk_SK', name: 'Slovak (Slovakia)'},
  {code: 'en_SH', name: 'English (St. Helena)'},
  {code: 'ti_ER', name: 'Tigrinya (Eritrea)'},
  {code: 'nd', name: 'North Ndebele'},
  {code: 'az_Cyrl_AZ', name: 'Azerbaijani (Cyrillic, Azerbaijan)'},
  {code: 'zu', name: 'Zulu'},
  {code: 'ne', name: 'Nepali'},
  {code: 'nd_ZW', name: 'North Ndebele (Zimbabwe)'},
  {code: 'el_CY', name: 'Greek (Cyprus)'},
  {code: 'en_IT', name: 'English (Italy)'},
  {code: 'nl_BQ', name: 'Dutch (Caribbean Netherlands)'},
  {code: 'da_GL', name: 'Danish (Greenland)'},
  {code: 'ja', name: 'Japanese'},
  {code: 'rm', name: 'Romansh'},
  {code: 'fr_ML', name: 'French (Mali)'},
  {code: 'rn', name: 'Rundi'},
  {code: 'en_VU', name: 'English (Vanuatu)'},
  {code: 'rof_TZ', name: 'Rombo (Tanzania)'},
  {code: 'ro', name: 'Romanian'},
  {code: 'ebu_KE', name: 'Embu (Kenya)'},
  {code: 'ru_KG', name: 'Russian (Kyrgyzstan)'},
  {code: 'en_SI', name: 'English (Slovenia)'},
  {code: 'sg_CF', name: 'Sango (Central African Republic)'},
  {code: 'mfe_MU', name: 'Morisyen (Mauritius)'},
  {code: 'nl', name: 'Dutch'},
  {code: 'brx', name: 'Bodo'},
  {code: 'bs_Latn', name: 'Bosnian (Latin)'},
  {code: 'fa', name: 'Persian'},
  {code: 'zgh_MA', name: 'Standard Moroccan Tamazight (Morocco)'},
  {code: 'en_GM', name: 'English (Gambia)'},
  {code: 'shi_Latn', name: 'Tachelhit (Latin)'},
  {code: 'en_FI', name: 'English (Finland)'},
  {code: 'nn', name: 'Norwegian Nynorsk'},
  {code: 'en_EE', name: 'English (Estonia)'},
  {code: 'ru', name: 'Russian'},
  {code: 'yue', name: 'Cantonese'},
  {code: 'kam_KE', name: 'Kamba (Kenya)'},
  {code: 'fur', name: 'Friulian'},
  {code: 'vai_Vaii', name: 'Vai (Vai)'},
  {code: 'ar_ER', name: 'Arabic (Eritrea)'},
  {code: 'rw', name: 'Kinyarwanda'},
  {code: 'ti_ET', name: 'Tigrinya (Ethiopia)'},
  {code: 'ff', name: 'Fulah'},
  {code: 'luo', name: 'Luo'},
  {code: 'fa_AF', name: 'Persian (Afghanistan)'},
  {code: 'nl_CW', name: 'Dutch (Curaçao)'},
  {code: 'es_MQ', name: 'Spanish (Martinique)'},
  {code: 'en_HR', name: 'English (Croatia)'},
  {code: 'en_FJ', name: 'English (Fiji)'},
  {code: 'fi', name: 'Finnish'},
  {code: 'pt_MO', name: 'Portuguese (Macau [China])'},
  {code: 'be', name: 'Belarusian'},
  {code: 'en_US', name: 'English (United States)'},
  {code: 'en_TO', name: 'English (Tonga)'},
  {code: 'en_SK', name: 'English (Slovakia)'},
  {code: 'bg', name: 'Bulgarian'},
  {code: 'ru_BY', name: 'Russian (Belarus)'},
  {code: 'it_IT', name: 'Italian (Italy)'},
  {code: 'ml_IN', name: 'Malayalam (India)'},
  {code: 'gsw_CH', name: 'Swiss German (Switzerland)'},
  {code: 'qu_EC', name: 'Quechua (Ecuador)'},
  {code: 'fo', name: 'Faroese'},
  {code: 'sv_FI', name: 'Swedish (Finland)'},
  {code: 'en_FK', name: 'English (Falkland Islands)'},
  {code: 'nus', name: 'Nuer'},
  {code: 'ta_LK', name: 'Tamil (Sri Lanka)'},
  {code: 'vun', name: 'Vunjo'},
  {code: 'sr_Latn', name: 'Serbian (Latin)'},
  {code: 'es_BZ', name: 'Spanish (Belize)'},
  {code: 'fr', name: 'French'},
  {code: 'en_SL', name: 'English (Sierra Leone)'},
  {code: 'bm', name: 'Bambara'},
  {code: 'es_VC', name: 'Spanish (St. Vincent & Grenadines)'},
  {code: 'ar_BH', name: 'Arabic (Bahrain)'},
  {code: 'guz', name: 'Gusii'},
  {code: 'bn', name: 'Bangla'},
  {code: 'bo', name: 'Tibetan'},
  {code: 'ar_SY', name: 'Arabic (Syria)'},
  {code: 'es_MS', name: 'Spanish (Montserrat)'},
  {code: 'lo_LA', name: 'Lao (Laos)'},
  {code: 'ne_NP', name: 'Nepali (Nepal)'},
  {code: 'uz_Latn', name: 'Uzbek (Latin)'},
  {code: 'be_BY', name: 'Belarusian (Belarus)'},
  {code: 'es_IC', name: 'Spanish (Canary Islands)'},
  {code: 'sr_Latn_XK', name: 'Serbian (Latin, Kosovo)'},
  {code: 'ar_MA', name: 'Arabic (Morocco)'},
  {code: 'pa_Guru_IN', name: 'Punjabi (Gurmukhi, India)'},
  {code: 'br', name: 'Breton'},
  {code: 'luy', name: 'Luyia'},
  {code: 'kde_TZ', name: 'Makonde (Tanzania)'},
  {code: 'es_AW', name: 'Spanish (Aruba)'},
  {code: 'bs', name: 'Bosnian'},
  {code: 'fy', name: 'Western Frisian'},
  {code: 'fur_IT', name: 'Friulian (Italy)'},
  {code: 'hu_HU', name: 'Hungarian (Hungary)'},
  {code: 'ar_AE', name: 'Arabic (United Arab Emirates)'},
  {code: 'en_HU', name: 'English (Hungary)'},
  {code: 'sah_RU', name: 'Sakha (Russia)'},
  {code: 'zh_Hans', name: 'Chinese (Simplified)'},
  {code: 'en_FM', name: 'English (Micronesia)'},
  {code: 'fr_MQ', name: 'French (Martinique)'},
  {code: 'ko_KP', name: 'Korean (North Korea)'},
  {code: 'en_150', name: 'English (Europe)'},
  {code: 'en_DE', name: 'English (Germany)'},
  {code: 'ce_RU', name: 'Chechen (Russia)'},
  {code: 'en_CA', name: 'English (Canada)'},
  {code: 'hsb_DE', name: 'Upper Sorbian (Germany)'},
  {code: 'sq_AL', name: 'Albanian (Albania)'},
  {code: 'en_TR', name: 'English (Turkey)'},
  {code: 'ro_MD', name: 'Romanian (Moldova)'},
  {code: 'es_VE', name: 'Spanish (Venezuela)'},
  {code: 'tg_TJ', name: 'Tajik (Tajikistan)'},
  {code: 'fr_WF', name: 'French (Wallis & Futuna)'},
  {code: 'mt_MT', name: 'Maltese (Malta)'},
  {code: 'kab', name: 'Kabyle'},
  {code: 'nmg_CM', name: 'Kwasio (Cameroon)'},
  {code: 'ms_SG', name: 'Malay (Singapore)'},
  {code: 'en_GR', name: 'English (Greece)'},
  {code: 'ru_UA', name: 'Russian (Ukraine)'},
  {code: 'fr_MR', name: 'French (Mauritania)'},
  {code: 'zh_Hans_MO', name: 'Chinese (Simplified, Macau [China])'},
  {code: 'de_IT', name: 'German (Italy)'},
  {code: 'ff_GN', name: 'Fulah (Guinea)'},
  {code: 'bs_Cyrl', name: 'Bosnian (Cyrillic)'},
  {code: 'nds_NL', name: 'Low German (Netherlands)'},
  {code: 'es_KN', name: 'Spanish (St. Kitts & Nevis)'},
  {code: 'sw_UG', name: 'Swahili (Uganda)'},
  {code: 'yue_Hans', name: 'Cantonese (Simplified)'},
  {code: 'ko_KR', name: 'Korean (South Korea)'},
  {code: 'en_DG', name: 'English (Diego Garcia)'},
  {code: 'bo_IN', name: 'Tibetan (India)'},
  {code: 'en_CC', name: 'English (Cocos [Keeling] Islands)'},
  {code: 'shi_Tfng_MA', name: 'Tachelhit (Tifinagh, Morocco)'},
  {code: 'lag', name: 'Langi'},
  {code: 'it_SM', name: 'Italian (San Marino)'},
  {code: 'os_RU', name: 'Ossetic (Russia)'},
  {code: 'en_TT', name: 'English (Trinidad & Tobago)'},
  {code: 'ms_Arab_MY', name: 'Malay (Arabic, Malaysia)'},
  {code: 'sq_MK', name: 'Albanian (Macedonia)'},
  {code: 'es_VG', name: 'Spanish (British Virgin Islands)'},
  {code: 'bem_ZM', name: 'Bemba (Zambia)'},
  {code: 'kde', name: 'Makonde'},
  {code: 'ar_OM', name: 'Arabic (Oman)'},
  {code: 'kk_KZ', name: 'Kazakh (Kazakhstan)'},
  {code: 'cgg', name: 'Chiga'},
  {code: 'bas', name: 'Basaa'},
  {code: 'kam', name: 'Kamba'},
  {code: 'wae', name: 'Walser'},
  {code: 'es_MX', name: 'Spanish (Mexico)'},
  {code: 'sah', name: 'Sakha'},
  {code: 'zh_Hant', name: 'Chinese (Traditional)'},
  {code: 'en_GU', name: 'English (Guam)'},
  {code: 'fr_MU', name: 'French (Mauritius)'},
  {code: 'fr_KM', name: 'French (Comoros)'},
  {code: 'ar_LB', name: 'Arabic (Lebanon)'},
  {code: 'en_BA', name: 'English (Bosnia & Herzegovina)'},
  {code: 'en_TV', name: 'English (Tuvalu)'},
  {code: 'sr_Cyrl', name: 'Serbian (Cyrillic)'},
  {code: 'mzn_IR', name: 'Mazanderani (Iran)'},
  {code: 'es_VI', name: 'Spanish (U.S. Virgin Islands)'},
  {code: 'dje', name: 'Zarma'},
  {code: 'kab_DZ', name: 'Kabyle (Algeria)'},
  {code: 'fil_PH', name: 'Filipino (Philippines)'},
  {code: 'se_SE', name: 'Northern Sami (Sweden)'},
  {code: 'vai', name: 'Vai'},
  {code: 'hr_HR', name: 'Croatian (Croatia)'},
  {code: 'bs_Latn_BA', name: 'Bosnian (Latin, Bosnia & Herzegovina)'},
  {code: 'nl_AW', name: 'Dutch (Aruba)'},
  {code: 'dav', name: 'Taita'},
  {code: 'so_SO', name: 'Somali (Somalia)'},
  {code: 'ar_PS', name: 'Arabic (Palestinian Territories)'},
  {code: 'en_FR', name: 'English (France)'},
  {code: 'uz_Cyrl', name: 'Uzbek (Cyrillic)'},
  {code: 'ff_SN', name: 'Fulah (Senegal)'},
  {code: 'en_BB', name: 'English (Barbados)'},
  {code: 'ki_KE', name: 'Kikuyu (Kenya)'},
  {code: 'en_TW', name: 'English (Taiwan)'},
  {code: 'naq', name: 'Nama'},
  {code: 'en_SS', name: 'English (South Sudan)'},
  {code: 'mg_MG', name: 'Malagasy (Madagascar)'},
  {code: 'mas_KE', name: 'Masai (Kenya)'},
  {code: 'en_RO', name: 'English (Romania)'},
  {code: 'en_PG', name: 'English (Papua New Guinea)'},
  {code: 'mgh', name: 'Makhuwa-Meetto'},
  {code: 'dyo_SN', name: 'Jola-Fonyi (Senegal)'},
  {code: 'mas', name: 'Masai'},
  {code: 'agq', name: 'Aghem'},
  {code: 'bn_BD', name: 'Bangla (Bangladesh)'},
  {code: 'haw', name: 'Hawaiian'},
  {code: 'yi', name: 'Yiddish'},
  {code: 'nb_NO', name: 'Norwegian Bokmål (Norway)'},
  {code: 'da_DK', name: 'Danish (Denmark)'},
  {code: 'en_DK', name: 'English (Denmark)'},
  {code: 'saq', name: 'Samburu'},
  {code: 'ug', name: 'Uyghur'},
  {code: 'cy_GB', name: 'Welsh (United Kingdom)'},
  {code: 'fr_YT', name: 'French (Mayotte)'},
  {code: 'jmc', name: 'Machame'},
  {code: 'ses_ML', name: 'Koyraboro Senni (Mali)'},
  {code: 'en_PH', name: 'English (Philippines)'},
  {code: 'de_DE', name: 'German (Germany)'},
  {code: 'ar_YE', name: 'Arabic (Yemen)'},
  {code: 'es_TC', name: 'Spanish (Turks & Caicos Islands)'},
  {code: 'bm_ML', name: 'Bambara (Mali)'},
  {code: 'yo', name: 'Yoruba'},
  {code: 'lkt_US', name: 'Lakota (United States)'},
  {code: 'uz_Arab_AF', name: 'Uzbek (Arabic, Afghanistan)'},
  {code: 'jgo', name: 'Ngomba'},
  {code: 'sl_SI', name: 'Slovenian (Slovenia)'},
  {code: 'pt_LU', name: 'Portuguese (Luxembourg)'},
  {code: 'uk', name: 'Ukrainian'},
  {code: 'en_CH', name: 'English (Switzerland)'},
  {code: 'asa', name: 'Asu'},
  {code: 'en_BD', name: 'English (Bangladesh)'},
  {code: 'lg_UG', name: 'Ganda (Uganda)'},
  {code: 'nds', name: 'Low German'},
  {code: 'qu_PE', name: 'Quechua (Peru)'},
  {code: 'mgo', name: 'Metaʼ'},
  {code: 'id_ID', name: 'Indonesian (Indonesia)'},
  {code: 'en_NA', name: 'English (Namibia)'},
  {code: 'en_GY', name: 'English (Guyana)'},
  {code: 'zgh', name: 'Standard Moroccan Tamazight'},
  {code: 'pt_MZ', name: 'Portuguese (Mozambique)'},
  {code: 'fr_LU', name: 'French (Luxembourg)'},
  {code: 'dsb', name: 'Lower Sorbian'},
  {code: 'mas_TZ', name: 'Masai (Tanzania)'},
  {code: 'en_DM', name: 'English (Dominica)'},
  {code: 'ta_MY', name: 'Tamil (Malaysia)'},
  {code: 'es_GD', name: 'Spanish (Grenada)'},
  {code: 'en_BE', name: 'English (Belgium)'},
  {code: 'mg', name: 'Malagasy'},
  {code: 'ur', name: 'Urdu'},
  {code: 'fr_GA', name: 'French (Gabon)'},
  {code: 'ka_GE', name: 'Georgian (Georgia)'},
  {code: 'nmg', name: 'Kwasio'},
  {code: 'en_TZ', name: 'English (Tanzania)'},
  {code: 'eu_ES', name: 'Basque (Spain)'},
  {code: 'ar_DZ', name: 'Arabic (Algeria)'},
  {code: 'id', name: 'Indonesian'},
  {code: 'so_DJ', name: 'Somali (Djibouti)'},
  {code: 'hsb', name: 'Upper Sorbian'},
  {code: 'yav', name: 'Yangben'},
  {code: 'mk', name: 'Macedonian'},
  {code: 'pa_Arab_PK', name: 'Punjabi (Arabic, Pakistan)'},
  {code: 'ml', name: 'Malayalam'},
  {code: 'en_ER', name: 'English (Eritrea)'},
  {code: 'ig', name: 'Igbo'},
  {code: 'se_FI', name: 'Northern Sami (Finland)'},
  {code: 'mn', name: 'Mongolian'},
  {code: 'ksb', name: 'Shambala'},
  {code: 'uz', name: 'Uzbek'},
  {code: 'vi_VN', name: 'Vietnamese (Vietnam)'},
  {code: 'ii', name: 'Sichuan Yi'},
  {code: 'qu', name: 'Quechua'},
  {code: 'en_PK', name: 'English (Pakistan)'},
  {code: 'ee', name: 'Ewe'},
  {code: 'ast_ES', name: 'Asturian (Spain)'},
  {code: 'yue_Hant', name: 'Cantonese (Traditional)'},
  {code: 'mr', name: 'Marathi'},
  {code: 'ms', name: 'Malay'},
  {code: 'en_ES', name: 'English (Spain)'},
  {code: 'ha_GH', name: 'Hausa (Ghana)'},
  {code: 'it_CH', name: 'Italian (Switzerland)'},
  {code: 'sq_XK', name: 'Albanian (Kosovo)'},
  {code: 'mt', name: 'Maltese'},
  {code: 'en_CK', name: 'English (Cook Islands)'},
  {code: 'br_FR', name: 'Breton (France)'},
  {code: 'en_BG', name: 'English (Bulgaria)'},
  {code: 'es_GF', name: 'Spanish (French Guiana)'},
  {code: 'tk_TM', name: 'Turkmen (Turkmenistan)'},
  {code: 'sr_Cyrl_XK', name: 'Serbian (Cyrillic, Kosovo)'},
  {code: 'ksf', name: 'Bafia'},
  {code: 'en_SX', name: 'English (Sint Maarten)'},
  {code: 'bg_BG', name: 'Bulgarian (Bulgaria)'},
  {code: 'en_PL', name: 'English (Poland)'},
  {code: 'af', name: 'Afrikaans'},
  {code: 'el', name: 'Greek'},
  {code: 'cs_CZ', name: 'Czech (Czechia)'},
  {code: 'fr_TD', name: 'French (Chad)'},
  {code: 'zh_Hans_HK', name: 'Chinese (Simplified, Hong Kong [China])'},
  {code: 'is', name: 'Icelandic'},
  {code: 'ksh', name: 'Colognian'},
  {code: 'my', name: 'Burmese'},
  {code: 'mn_MN', name: 'Mongolian (Mongolia)'},
  {code: 'en', name: 'English'},
  {code: 'it', name: 'Italian'},
  {code: 'dsb_DE', name: 'Lower Sorbian (Germany)'},
  {code: 'ii_CN', name: 'Sichuan Yi (China)'},
  {code: 'eo', name: 'Esperanto'},
  {code: 'iu', name: 'Inuktitut'},
  {code: 'en_ZA', name: 'English (South Africa)'},
  {code: 'smn', name: 'Inari Sami'},
  {code: 'en_AD', name: 'English (Andorra)'},
  {code: 'ak', name: 'Akan'},
  {code: 'en_RU', name: 'English (Russia)'},
  {code: 'kkj_CM', name: 'Kako (Cameroon)'},
  {code: 'am', name: 'Amharic'},
  {code: 'es', name: 'Spanish'},
  {code: 'et', name: 'Estonian'},
  {code: 'uk_UA', name: 'Ukrainian (Ukraine)'},
];
